module.exports = {
  PIN_CAMERA_SERVO_1: 9,
  PIN_CAMERA_SERVO_2: 10,

  PIN_PROXIMITY_1: 'A0',
  PIN_PROXIMITY_2: 'A1',
  PIN_PROXIMITY_3: 3,
  PIN_PROXIMITY_4: 11,

  PIN_MOTOR_LEFT_ENCODER_SENSOR: 'A2',
  PIN_MOTOR_RIGHT_ENCODER_SENSOR: 'A3',

  PIN_RIGHT_DIR: 7,
  PIN_RIGHT_SPEED: 6,

  PIN_LEFT_DIR: 4,
  PIN_LEFT_SPEED: 5,

  PIN_STEPPER1: [12, 11, 10, 9]
}
