module.exports = {
  PIN_CAMERA_SERVO_1: 9,
  PIN_CAMERA_SERVO_2: 10,
  PIN_PROXIMITY_1: 3,
  PIN_PROXIMITY_2: 11,

  PIN_LEFT_DIR: 7,
  PIN_LEFT_SPEED: 6,

  PIN_RIGHT_DIR: 4,
  PIN_RIGHT_SPEED: 5,

  PIN_STEPPER1: [12, 11, 10, 9]
}
